# Silly Mac, see https://stackoverflow.com/a/41054093
export GPG_TTY=$(tty)

# User specific aliases and functions
. ~/.dotfiles/mac/aliases.zsh

setopt histignoredups
setopt histignorespace

bindkey -v
bindkey "^R" history-incremental-search-backward

export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
export EDITOR=nvim

# load homebrew completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit -C
fi

eval "$(mise activate zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
