# User specific aliases and functions
. ~/.dotfiles/linux/aliases.zsh

setopt histignoredups
setopt histignorespace

bindkey -v
bindkey "^R" history-incremental-search-backward
bindkey "^?" backward-delete-char

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
export EDITOR=nvim
export PAGER=/bin/less
export PATH="$HOME/.local/bin:$PATH"

# rust config
. $HOME/.cargo/env
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-$(arch)-unknown-linux-gnu/lib/rustlib/src/rust/library"

autoload -Uz compinit
compinit

eval "$(mise activate zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
